#!/usr/bin/env bash

export CONTECO_LABEL="module.ksql_server_tocloud - ContEco"
export CONTECO_DESCRIPTION="ContEco KSQL Server to cloud module with managed standard URL UI."

export CONTECO_TYPE="module"
export CONTECO_NAME="ksql_server_tocloud"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
