#!/usr/bin/env bash

export CONTECO_LABEL="module.ksql_server_sasl - ContEco"
export CONTECO_DESCRIPTION="ContEco Confluent KSQL server module, with SASL authentication."

export CONTECO_TYPE="module"
export CONTECO_NAME="ksql_server_sasl"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
